global using Fastrup.Bowling.Domain.Abstractions;
global using Fastrup.Bowling.Domain.Events;
global using Fastrup.Bowling.Domain.Exceptions;
global using Fastrup.Bowling.Domain.Model;
global using Fastrup.Bowling.Domain.Model.Game;
global using Fastrup.Bowling.Domain.Model.Player;
global using Fastrup.Bowling.Domain.Model.Score;
global using FluentAssertions;
global using Xunit;
